version: '3.4'
services:
  database:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD:  123OwTeste987
      MYSQL_DATABASE: owmovimentacoes
      MYSQL_USER: owteste
      MYSQL_PASSWORD: 123456Ow
    volumes:
      - ${PWD}/db-files:/var/lib/mysql
    ports: 
      - 3308:3306
    restart: on-failure
    container-name: ow-teste